module.exports={
  google:{
    clientID:process.env.Google_ClientID,
    clientSecret:process.env.Google_ClientSecret
  },
  facebook:{
    appID:process.env.Facebook_appID,
    appSecret:process.env.Facebook_appSecret
  },
  twitter:{
    consumerKey:process.env.Twitter_ConsumerKey,
    consumerSecret:process.env.Twitter_ConsumerSecret
  },
  mongodb:{
    dbURI:process.env.dbURI
  },
  session:{
    cookieKey:process.env.cookieKey
  }
};
